spring.application.name=search

# Jackson JSON Settings
spring.jackson.property-naming-strategy=SNAKE_CASE

# Civil Service Sync Settings
civilservice.sync.url=https://data.cityofnewyork.us/api/v3/views/a9md-ynri/query.json
civilservice.sync.limit=-1
civilservice.sync.cron=0 0 2 * * ?
civilservice.sync.batch-size=20000
civilservice.sync.app-token=${CIVILSERVICE_SYNC_APP_TOKEN:}
civilservice.sync.secret-token=${CIVILSERVICE_SYNC_SECRET_TOKEN:}

# Civil Service List Sync Settings (Active & Terminated candidates)
civilservice.sync.list.active-dataset-id=vx8i-nprf
civilservice.sync.list.terminated-dataset-id=qu8g-sxqf
civilservice.sync.list.limit=-1

# Hibernate Search Properties (Standalone)
hibernate.search.backend.directory.root=./lucene-index

# Linear Regression and Prediction settings
civilservice.predict.skip-threshold=1.5
civilservice.predict.default-days-per-rank=2.0


